# Generated by Django 4.2.26 on 2025-11-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="Descripción corta"),
                ),
                ("description", models.TextField(verbose_name="Descripción completa")),
                (
                    "technologies",
                    models.CharField(max_length=300, verbose_name="Tecnologías"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("datos", "Análisis de Datos y BI"),
                            ("gestion", "Gestión de Proyectos y Procesos"),
                            ("desarrollo", "Desarrollo Web y Software"),
                            ("infra", "Infraestructura y Soporte"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de GitHub"
                    ),
                ),
                (
                    "live_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del sitio en vivo"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        upload_to="projects/covers/", verbose_name="Imagen de portada"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="¿Es destacado?"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "icon_svg",
                    models.TextField(
                        blank=True,
                        help_text="Código SVG del ícono",
                        verbose_name="Ícono SVG",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("datos", "Datos"),
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("gestion", "Gestión"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/gallery/", verbose_name="Imagen"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de proyecto",
                "verbose_name_plural": "Imágenes de proyectos",
                "ordering": ["order"],
            },
        ),
    ]
