# Generated by Django 5.2.8 on 2025-11-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "organization",
                    models.CharField(max_length=200, verbose_name="Organización"),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("competition", "Competencia"),
                            ("certification", "Certificación"),
                            ("award", "Premio"),
                            ("recognition", "Reconocimiento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 3er Puesto, Gold Badge, etc.",
                        max_length=100,
                        verbose_name="Posición",
                    ),
                ),
                ("date_achieved", models.DateField(verbose_name="Fecha de logro")),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="achievements/certificates/",
                        verbose_name="Imagen del certificado",
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="achievements/badges/",
                        verbose_name="Imagen del badge",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de verificación"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="¿Es destacado?"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logro",
                "verbose_name_plural": "Logros",
                "ordering": ["-date_achieved", "order"],
            },
        ),
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "logo_type",
                    models.CharField(
                        choices=[
                            ("company", "Empresa"),
                            ("technology", "Tecnología"),
                            ("client", "Cliente"),
                            ("partner", "Partner"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de logo",
                    ),
                ),
                (
                    "logo_image",
                    models.ImageField(
                        upload_to="logos/", verbose_name="Imagen del logo"
                    ),
                ),
                (
                    "logo_svg",
                    models.TextField(
                        blank=True,
                        help_text="Versión SVG optimizada del logo",
                        verbose_name="Logo SVG",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL relacionada"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo",
                "verbose_name_plural": "Logos",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["order", "category", "name"],
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="video_demo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects/videos/",
                verbose_name="Video de demostración",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Contador de vistas"),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/thumbnails/",
                verbose_name="Miniatura",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="skills/icons/",
                verbose_name="Imagen del ícono",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AddField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                default=50,
                help_text="0-100 para la barra de progreso",
                verbose_name="Nivel de profundidad",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("datos", "Análisis de Datos y BI"),
                    ("gestion", "Gestión de Proyectos y Procesos"),
                    ("desarrollo", "Desarrollo Web y Software"),
                    ("infra", "Infraestructura y Soporte"),
                    ("ia", "Inteligencia Artificial y ML"),
                ],
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("datos", "Datos y BI"),
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("gestion", "Gestión"),
                    ("cloud", "Cloud & DevOps"),
                ],
                max_length=20,
                verbose_name="Categoría",
            ),
        ),
    ]
